name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write
      issues: write
    uses: crawlora/starter-apps/.github/workflows/publish.yaml@main
    secrets:
      auth_key: ${{ secrets.CRAWLORA_AUTH_KEY }}
